name: redis

addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm

instance_groups:
- name: redis
  azs: [z1]
  instances: 2
  vm_type: default
  stemcell: default
  persistent_disk: 10240
  networks: [{name: default}]
  jobs:
  - name: redis
    release: redis
    properties:
      password: ((redis-password))
- name: sanity-tests
  azs: [z1]
  instances: 1
  lifecycle: errand
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: sanity-tests
    release: redis

variables:
- name: redis-password
  type: password

update:
  canaries: 0
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-20000
  update_watch_time: 1000-20000

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

releases:
- name: bpm
  sha1: f2bd126b17b3591160f501d88d79ccf0aba1ae54
  url: git+https://github.com/cloudfoundry-incubator/bpm-release
  version: 1.0.4
- name: redis
  sha1: 7851118ef38a8393a70869b3b254e14ec4fd24a7
  stemcell:
    os: ubuntu-xenial
    version: "250.4"
  url: https://s3.amazonaws.com/redis-boshrelease/compiled-releases/redis/redis-15.2.4-ubuntu-xenial-250.4-20190130-060109-237608494-20190130060109.tgz
  version: 15.2.4
